name: Build WebAssembly

on:
  push:
    branches: [ main, master ]
    paths:
      - 'assembly/**'
      - 'package.json'
      - 'asconfig.json'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'assembly/**'
      - 'package.json'
      - 'asconfig.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build WebAssembly
        run: npm run asbuild

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: |
            build/debug.wasm
            build/release.wasm
          retention-days: 7 